# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=600)),
                ('edited', models.CharField(max_length=600)),
                ('created', models.CharField(max_length=600)),
            ],
        ),
    ]
