# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 01:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=ckeditor.fields.RichTextField(max_length=600),
        ),
    ]
