# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170731_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='example', max_length=100),
            preserve_default=False,
        ),
    ]
