# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='example', max_length=200, unique=True),
        ),
    ]
