# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20170728_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default='example', max_length=200),
        ),
    ]
