# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20170728_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='toc',
        ),
    ]
