# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_remove_article_toc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
