# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20170729_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=600),
        ),
    ]
