# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_article_editedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=150, verbose_name='djangodbmodelsfieldscharfield'),
        ),
    ]
