# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 06:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20170814_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='discussions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
