# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_article_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editedtime',
            field=models.CharField(default='default', max_length=999999999999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='editedby',
            field=models.CharField(max_length=999999999999),
        ),
    ]
